conda activate dmstrack

export MY_PROJECT=$PWD/../
export PYTHONPATH=${PYTHONPATH}:${MY_PROJECT}/AB3DMOT
export PYTHONPATH=${PYTHONPATH}:${MY_PROJECT}/AB3DMOT/Xinshuo_PyToolbox
export PYTHONPATH=${PYTHONPATH}:${MY_PROJECT}/V2V4Real
export PYTHONPATH=${PYTHONPATH}:${MY_PROJECT}/DMSTrack
export PYTHONPATH=${PYTHONPATH}:${MY_PROJECT}/

echo $PYTHONPATH
